services:
  - type: web
    name: daily-news-digest
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rake admin:create_user
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: DISABLE_DATABASE_ENVIRONMENT_CHECK
        value: "1"
  - type: redis
    name: redis
    plan: free
  - type: worker
    name: sidekiq
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: DISABLE_DATABASE_ENVIRONMENT_CHECK
        value: "1"

databases:
  - name: postgres
    plan: free