services:
  - type: web
    name: daily-news-digest
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true

databases:
  - name: postgres
    plan: free