name: RSpec Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      CHROME_BIN: /usr/bin/google-chrome
      CHROME_PATH: /usr/bin/google-chrome
      DISPLAY: :99

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    
    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libnss3 libgconf-2-4 libxss1 libasound2

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Set up Chromedriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        sleep 3  # Give xvfb time to start
    
    - name: Set up database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
    
    - name: Run tests
      run: |
        chromedriver --version
        chromedriver &
        sleep 3
        bundle exec rspec

    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-pages-artifact@v3
      with:
        name: capybara-screenshots
        path: tmp/capybara